remote_theme: jeromelachaud/grayscale-theme
image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/FLORIST_%28neon_sign%29.jpg"
title: technomancer-01.com
url: https://technomancer-01.com
description: "Art, Netrunning, and General Geekery from a Post-Y2K'er"
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Technomancer-01.com
