remote_theme: jeromelachaud/grayscale-theme

layout: post
title: Technomancer-01
tags: card, blogging
image: 
  path: https://raw.githubusercontent.com/ErikaVasNormandy/erikavasnormandy.github.io/master/img/tech-bun-transparent%20small.PNG
  width: 1200
  height: 630
  
  
title_separator: "-"
url: https://technomancer-01.com
description: "Illustration,  Netrunning, and General Geekery Post Y2K"
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Technomancer-01.com

#Social Media
twitter:
  username: technomancer_01
og_image: https://raw.githubusercontent.com/ErikaVasNormandy/erikavasnormandy.github.io/master/img/tech-bun-transparent%20small.PNG
