remote_theme: jeromelachaud/grayscale-theme
title: Technomancer-01
title_separator: "-"
url: https://technomancer-01.com
description: "Illustration, Netrunning, and General Geekery from a Post-Y2K'er"
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Technomancer-01.com

#Social Media
image: 
  path: https://cdna.artstation.com/p/assets/images/images/027/830/672/large/erika-hudiono-asset.jpg
twitter:
  username: technomancer_01
og_image: https://cdna.artstation.com/p/assets/images/images/027/830/672/large/erika-hudiono-asset.jpg
